name: Deploy to gold.vm.coreor.net

on:
  push:
    branches:
      - prod

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H gold.vm.coreor.net >> ~/.ssh/known_hosts

    - name: Deploy to Server
      run: |
        ssh battincik@gold.vm.coreor.net "
        cd ~/coreor-apps/bun-test &&
        git pull origin prod &&
        bun install &&
        pm2 restart bun-test
        "
